# Generated by Django 4.2.8 on 2024-01-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_department_activitygroup_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
