# Generated by Django 4.1.5 on 2024-01-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_activity_fine_amount_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='attendance',
        ),
        migrations.AddField(
            model_name='fine',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='api.activity'),
        ),
    ]
