# Generated by Django 4.2.8 on 2024-02-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_activity_allowed_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='status',
            field=models.CharField(default='unpaid', max_length=8),
        ),
    ]
