# Generated by Django 4.1.5 on 2024-02-25 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_fine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('removed', 'Removed')], default='unpaid', max_length=8),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(choices=[('unseen', 'unseen'), ('seen', 'Seen')], default='others', max_length=8)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('unseen', 'unseen'), ('seen', 'Seen')], default='unpaid', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
