# Generated by Django 4.1.5 on 2024-02-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_fine_status_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='relation',
            field=models.CharField(choices=[('fine', 'Fine'), ('activity', 'Activity'), ('others', 'Others')], default='others', max_length=8),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unseen', 'Unseen'), ('seen', 'Seen')], default='unpaid', max_length=8),
        ),
    ]
