# Generated by Django 4.2.8 on 2024-02-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(default='/', max_length=100),
            preserve_default=False,
        ),
    ]
