# Generated by Django 4.2.10 on 2024-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_department_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year_level',
            field=models.IntegerField(null=True),
        ),
    ]
