# Generated by Django 4.2.10 on 2024-05-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='semester',
            field=models.IntegerField(choices=[('1st', 1), ('2nd', 2)], default=1),
            preserve_default=False,
        ),
    ]
