# Generated by Django 4.2.10 on 2024-05-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_semester_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd')]),
        ),
    ]
